### PR TITLE
Use openocd to flash and debug

### LINKED ISSUE #79: Use openOCD as an alternative to program the LPC controller
We should avoid using commercial software to program our board, since it limits us in terms of flexibility.
A great option is to use openOCD as an interface working together with a USB-Serial converter (FTDI, Buspirate, etc) to program the chip.

### PR DESCRIPTION
**Pull request by Palmitoxico**
This should close #79

### CODE REVIEW

**Comment by Palmitoxico** [comment]
It seems that the original LPCLink doesn't support cmsis-dap / jlink, I'll bring support back for this probe. The LPCLink2 is fully supported by OpenOCD, provided it has the correct firmware preloaded on it.

**Comment by kaolpr** [comment]
Do you think that we could implement debugging via FTDI JTAG? MMC is in the chain, so it seems to be possible, however I have no experience with that, so I may be missing something.

**Comment by Palmitoxico** [comment]
Hi @kaolpr,

Unfortunately the MMC isn't in the FTDI JTAG chain. The schematics are a little confusing but the MMC JTAG interface is connected to the AMC JTAG interface when the payload power is off, not to the FT4223H.

**Comment by Palmitoxico** [comment]
Implemented in 3f684a10bbca44da944e4b14f23ccce40c3119e3

**Pull request closed without merging**
